import type { ProjectRecord } from "../schema";

export const lineFollower: ProjectRecord = {
  slug: "line-follower-robot",
  author: "roverlab",
  source: "seed",
  stars: 12,
  createdAt: "2026-08-24T15:40:00Z",
  cover: { glyph: "⛭", hueA: "#a78bfa", hueB: "#4ade80" },
  pkg: {
    name: "Line-Follower Robot",
    summary:
      "A differential-drive robot that tracks a 19mm black line on a light floor using a five-channel IR reflectance array held 8mm above the surface. A Raspberry Pi Pico samples all five channels, computes a weighted line position, and runs a PID loop that trims two N20 gearmotors through a DRV8833 H-bridge. A 1S LiPo pack feeds a 5V boost converter that supplies both the motor rail and the Pico, so cornering speed stays consistent as the pack drains rather than fading with cell voltage.",
    tags: ["DIFFERENTIAL DRIVE", "PID LINE TRACKING", "PRINTED CHASSIS", "LIPO POWERED"],
    parts: [
      {
        id: "pico",
        name: "Raspberry Pi Pico",
        role: "Main Logic Controller",
        description:
          "RP2040 board running the sensor sample loop and PID controller; four PWM slices drive the H-bridge inputs.",
        category: "mcu",
        domain: "electrical",
        qty: 1,
        unitCost: 4.0,
        pins: ["VSYS", "3V3", "GND", "GP2", "GP3", "GP4", "GP5", "GP6", "GP8", "GP9", "GP10", "GP11"],
      },
      {
        id: "ir-array",
        name: "5-Channel IR Reflectance Array",
        role: "Line Sensor",
        description:
          "Five phototransistor/emitter pairs on 9.5mm centres with analog outputs; reflectance drops sharply over the line.",
        category: "sensor",
        domain: "electrical",
        qty: 1,
        unitCost: 8.5,
        pins: ["VCC", "GND", "S1", "S2", "S3", "S4", "S5"],
      },
      {
        id: "drv8833",
        name: "DRV8833 Dual H-Bridge Carrier",
        role: "Motor Driver",
        description:
          "Two 1.5A bridges taking four PWM inputs; drives each gearmotor forward, reverse, or into slow decay braking.",
        category: "module",
        domain: "electrical",
        qty: 1,
        unitCost: 4.5,
        pins: ["VM", "GND", "AIN1", "AIN2", "BIN1", "BIN2", "AOUT1", "AOUT2", "BOUT1", "BOUT2"],
      },
      {
        id: "motor-left",
        name: "N20 Gearmotor 6V 200RPM (Left)",
        role: "Left Drive Motor",
        description: "Metal-gearbox micro motor on the left hub, 3mm D-shaft into the wheel boss.",
        category: "actuator",
        domain: "electrical",
        qty: 1,
        unitCost: 6.5,
        pins: ["M+", "M-"],
      },
      {
        id: "motor-right",
        name: "N20 Gearmotor 6V 200RPM (Right)",
        role: "Right Drive Motor",
        description: "Identical motor on the right hub; wired with reversed polarity so both wheels roll forward together.",
        category: "actuator",
        domain: "electrical",
        qty: 1,
        unitCost: 6.5,
        pins: ["M+", "M-"],
      },
      {
        id: "lipo",
        name: "1S 1200mAh LiPo Pack",
        role: "Energy Storage",
        description: "3.7V pouch cell with integrated protection, sized to clear the chassis pocket under the deck.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 9.0,
        pins: ["B+", "B-"],
      },
      {
        id: "power-switch",
        name: "SPDT Slide Power Switch",
        role: "Main Cutoff",
        description: "Panel switch breaking the pack's positive lead so the robot can be parked without unplugging the cell.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 1.2,
        pins: ["IN", "OUT"],
      },
      {
        id: "boost",
        name: "5V 2A Boost Converter",
        role: "5V Regulator",
        description:
          "Step-up module holding a stiff 5V rail from a draining 1S pack; feeds the motor bridge and the Pico together.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 3.5,
        pins: ["VIN", "GND", "VOUT"],
      },
      {
        id: "chassis-plate",
        name: "Chassis Plate",
        role: "Structural Deck",
        description:
          "Main deck carrying the motor mounts, electronics, and battery pocket, with a slotted boom mount for ride-height adjustment.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 4.0,
        printSettings: "PETG · 40% infill, 0.2mm layer, 4 perimeters",
      },
      {
        id: "sensor-boom",
        name: "Sensor Boom",
        role: "Array Carrier",
        description: "Forward boom holding the reflectance array flat and square to the floor ahead of the drive axle.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 1.2,
        printSettings: "PETG · 40% infill, 0.2mm layer",
      },
      {
        id: "motor-mount",
        name: "N20 Motor Mounts",
        role: "Drive Mounts",
        description: "Mirrored clamp pockets that hold each N20 gearbox square to the deck and set the wheel track.",
        category: "print3d",
        domain: "mechanical",
        qty: 2,
        unitCost: 0.9,
        printSettings: "PETG · 60% infill, 0.2mm layer, 5 perimeters",
      },
      {
        id: "caster-mount",
        name: "Ball Caster Mount",
        role: "Rear Support",
        description: "Rear pedestal setting the caster height so the deck sits level with the drive wheels.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 0.7,
        printSettings: "PETG · 50% infill, 0.2mm layer",
      },
      {
        id: "wheels",
        name: "32mm Rubber Drive Wheels",
        role: "Traction",
        description: "Soft-tyre wheels on 3mm D-bores; the rubber compound matters more than diameter for tight corners.",
        category: "misc",
        domain: "mechanical",
        qty: 2,
        unitCost: 2.2,
      },
      {
        id: "ball-caster",
        name: "10mm Ball Caster",
        role: "Third Contact Point",
        description: "Free-rolling metal ball in a plastic socket, giving low-friction support without steering resistance.",
        category: "misc",
        domain: "mechanical",
        qty: 1,
        unitCost: 1.8,
      },
      {
        id: "m2-hardware",
        name: "M2/M3 Screws + Nylon Standoffs",
        role: "Fastener Set",
        description: "M2 screws for the motor and boom mounts, M3 standoffs lifting the boards clear of the deck.",
        category: "misc",
        domain: "mechanical",
        qty: 20,
        unitCost: 0.15,
      },
    ],
    connections: [
      { id: "c1", from: { part: "lipo", pin: "B+" }, to: { part: "power-switch", pin: "IN" }, net: "power", label: "3.7V" },
      { id: "c2", from: { part: "power-switch", pin: "OUT" }, to: { part: "boost", pin: "VIN" }, net: "power", label: "VBAT" },
      { id: "c3", from: { part: "lipo", pin: "B-" }, to: { part: "boost", pin: "GND" }, net: "ground" },
      { id: "c4", from: { part: "boost", pin: "VOUT" }, to: { part: "pico", pin: "VSYS" }, net: "power", label: "5V" },
      { id: "c5", from: { part: "boost", pin: "GND" }, to: { part: "pico", pin: "GND" }, net: "ground" },
      { id: "c6", from: { part: "boost", pin: "VOUT" }, to: { part: "drv8833", pin: "VM" }, net: "power", label: "5V" },
      { id: "c7", from: { part: "boost", pin: "GND" }, to: { part: "drv8833", pin: "GND" }, net: "ground" },
      { id: "c8", from: { part: "pico", pin: "3V3" }, to: { part: "ir-array", pin: "VCC" }, net: "power", label: "3.3V" },
      { id: "c9", from: { part: "pico", pin: "GND" }, to: { part: "ir-array", pin: "GND" }, net: "ground" },
      { id: "c10", from: { part: "ir-array", pin: "S1" }, to: { part: "pico", pin: "GP2" }, net: "data", label: "analog" },
      { id: "c11", from: { part: "ir-array", pin: "S2" }, to: { part: "pico", pin: "GP3" }, net: "data", label: "analog" },
      { id: "c12", from: { part: "ir-array", pin: "S3" }, to: { part: "pico", pin: "GP4" }, net: "data", label: "analog" },
      { id: "c13", from: { part: "ir-array", pin: "S4" }, to: { part: "pico", pin: "GP5" }, net: "data", label: "analog" },
      { id: "c14", from: { part: "ir-array", pin: "S5" }, to: { part: "pico", pin: "GP6" }, net: "data", label: "analog" },
      { id: "c15", from: { part: "pico", pin: "GP8" }, to: { part: "drv8833", pin: "AIN1" }, net: "data", label: "PWM" },
      { id: "c16", from: { part: "pico", pin: "GP9" }, to: { part: "drv8833", pin: "AIN2" }, net: "data", label: "PWM" },
      { id: "c17", from: { part: "pico", pin: "GP10" }, to: { part: "drv8833", pin: "BIN1" }, net: "data", label: "PWM" },
      { id: "c18", from: { part: "pico", pin: "GP11" }, to: { part: "drv8833", pin: "BIN2" }, net: "data", label: "PWM" },
      { id: "c19", from: { part: "drv8833", pin: "AOUT1" }, to: { part: "motor-left", pin: "M+" }, net: "power", label: "bridge A" },
      { id: "c20", from: { part: "drv8833", pin: "AOUT2" }, to: { part: "motor-left", pin: "M-" }, net: "power", label: "bridge A" },
      { id: "c21", from: { part: "drv8833", pin: "BOUT1" }, to: { part: "motor-right", pin: "M+" }, net: "power", label: "bridge B" },
      { id: "c22", from: { part: "drv8833", pin: "BOUT2" }, to: { part: "motor-right", pin: "M-" }, net: "power", label: "bridge B" },
    ],
    assembly: [
      {
        part: "chassis-plate",
        children: [
          { part: "motor-mount", children: [{ part: "motor-left" }, { part: "motor-right" }] },
          { part: "wheels" },
          { part: "caster-mount", children: [{ part: "ball-caster" }] },
          { part: "sensor-boom", children: [{ part: "ir-array" }] },
          { part: "pico" },
          { part: "drv8833" },
          { part: "boost" },
          { part: "power-switch" },
          { part: "lipo" },
          { part: "m2-hardware" },
        ],
      },
    ],
    tools: [
      "3D printer (PLA or PETG)",
      "Soldering station with fine tip",
      "Wire strippers",
      "Flush cutters",
      "M2 hex driver",
      "Digital multimeter",
      "Micro-USB cable",
      "Calipers",
    ],
    assumptions: [
      "A matte light-coloured floor with a 19mm black tape or printed track",
      "A 1S LiPo balance charger; the robot has no onboard charging",
      "Track corners no tighter than 150mm radius at the tuned speed",
      "Basic familiarity with MicroPython or the Pico C SDK",
    ],
    instructions: [
      {
        id: "1",
        title: "Fabricate",
        steps: [
          {
            id: "1.1",
            title: "Print the deck, boom, and mounts",
            detail:
              "Print the chassis plate, sensor boom, both motor mounts, and the caster pedestal. The motor mounts want 5 perimeters — a flexing pocket lets the gearbox rock and shows up as steering wander.",
            tools: ["3D printer (PLA or PETG)"],
            parts: ["chassis-plate", "sensor-boom", "motor-mount", "caster-mount"],
          },
          {
            id: "1.2",
            title: "Fit-check motors and wheel clearance",
            detail:
              "Test the gearbox into each mount pocket and measure the wheel-to-deck gap; 2mm is enough. Trim elephant's foot off the first layer rather than forcing the fit.",
            tools: ["Calipers", "Flush cutters"],
            parts: ["motor-mount", "motor-left", "motor-right", "wheels"],
          },
          {
            id: "1.3",
            title: "Install standoffs and the rear caster",
            detail:
              "Screw the nylon standoffs into the deck for the Pico and driver, then bolt the caster into its pedestal and check the deck sits level on a flat surface.",
            tools: ["M2 hex driver"],
            parts: ["chassis-plate", "caster-mount", "ball-caster", "m2-hardware"],
          },
        ],
      },
      {
        id: "2",
        title: "Wire",
        steps: [
          {
            id: "2.1",
            title: "Solder the battery and boost chain",
            detail:
              "Pack positive through the slide switch into the boost input, pack negative straight to boost ground. Tin and insulate one LiPo lead at a time — never leave both bare leads exposed near the iron.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["lipo", "power-switch", "boost"],
          },
          {
            id: "2.2",
            title: "Wire the motor driver and gearmotors",
            detail:
              "Run 5V and ground from the boost output to VM/GND, then the two bridge output pairs to the motors. Twist each motor pair to keep commutation noise off the sensor leads.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["drv8833", "boost", "motor-left", "motor-right"],
          },
          {
            id: "2.3",
            title: "Wire the reflectance array",
            detail:
              "3.3V and ground from the Pico to the array, then S1-S5 to GP2-GP6 in physical left-to-right order — a swapped channel inverts the error term and the robot drives off the line.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["ir-array", "pico", "sensor-boom"],
          },
          {
            id: "2.4",
            title: "Verify rails before first power-up",
            detail:
              "With the switch off, confirm no continuity between 5V and ground; switch on and check 5.0V at both the Pico and the driver before connecting USB.",
            tools: ["Digital multimeter"],
            parts: ["boost", "pico", "drv8833"],
          },
        ],
      },
      {
        id: "3",
        title: "Bring-up",
        steps: [
          {
            id: "3.1",
            title: "Flash the control firmware",
            detail:
              "Hold BOOTSEL, flash the line-follower firmware, and confirm the serial console prints raw sensor counts at the loop rate you expect.",
            tools: ["Micro-USB cable"],
            parts: ["pico"],
          },
          {
            id: "3.2",
            title: "Calibrate the array",
            detail:
              "Sweep the boom across the line and back so every channel sees both extremes, then store the per-channel min/max used to normalise readings.",
            tools: ["Micro-USB cable"],
            parts: ["ir-array", "pico"],
          },
          {
            id: "3.3",
            title: "Check motor direction and balance",
            detail:
              "With the robot on a stand, command equal forward duty and confirm both wheels spin forward at similar speed; swap one motor's leads if it runs backwards.",
            tools: ["Micro-USB cable", "Digital multimeter"],
            parts: ["pico", "drv8833", "motor-left", "motor-right"],
          },
          {
            id: "3.4",
            title: "Tune the PID gains",
            detail:
              "Raise proportional gain until the robot oscillates on a straight, back it off a third, then add derivative to damp the corner exit. Leave integral near zero unless the track has long constant curves.",
            tools: ["Micro-USB cable"],
            parts: ["pico", "ir-array", "motor-left", "motor-right"],
          },
        ],
      },
      {
        id: "4",
        title: "Assemble",
        steps: [
          {
            id: "4.1",
            title: "Mount the drivetrain",
            detail:
              "Bolt both motor mounts to the deck, seat the gearmotors, and press the wheels onto the D-shafts until the hub bottoms out.",
            tools: ["M2 hex driver"],
            parts: ["chassis-plate", "motor-mount", "motor-left", "motor-right", "wheels"],
          },
          {
            id: "4.2",
            title: "Set the sensor boom ride height",
            detail:
              "Slide the boom in its slot until the array sits 8mm above the floor and square to it, then lock both screws. Height changes the contrast far more than any gain you can tune.",
            tools: ["M2 hex driver", "Calipers"],
            parts: ["sensor-boom", "ir-array", "m2-hardware"],
          },
          {
            id: "4.3",
            title: "Stow the pack and dress the wiring",
            detail:
              "Drop the LiPo into the deck pocket, mount the switch at the rear edge, and trim the harness so nothing hangs into the wheel arc before the first full-speed lap.",
            tools: ["Flush cutters", "M2 hex driver"],
            parts: ["chassis-plate", "lipo", "power-switch", "boost", "pico", "drv8833"],
          },
        ],
      },
    ],
  },
};
