import type { ProjectRecord } from "../schema";

export const planter: ProjectRecord = {
  slug: "self-watering-planter",
  author: "greenloop",
  source: "seed",
  stars: 5,
  createdAt: "2026-08-05T08:20:00Z",
  cover: { glyph: "❀", hueA: "#4ade80", hueB: "#22d3ee" },
  pkg: {
    name: "Self-Watering Planter",
    summary:
      "A single-pot irrigation controller that reads a capacitive probe buried in the root zone and runs a submersible pump for a measured dose whenever the soil dries past a threshold. An ESP32-C3 switches the pump through a logic-level MOSFET board, waits for the moisture reading to settle before deciding again, and publishes soil, dose, and reservoir state over Wi-Fi. A float switch in the reservoir blocks the pump outright when the water runs low, so a forgotten refill never turns into a dry-running pump.",
    tags: ["WI-FI ALERTS", "MOISTURE FEEDBACK", "DRY-RUN PROTECTION", "MAINS POWERED"],
    parts: [
      {
        id: "esp32c3",
        name: "ESP32-C3 Super Mini",
        role: "Main Logic Controller",
        description:
          "Wi-Fi microcontroller running the irrigation state machine. Its onboard regulator takes the 5V input down to the 3.3V rail that feeds the probe.",
        category: "mcu",
        domain: "electrical",
        qty: 1,
        unitCost: 4.2,
        pins: ["5V", "3V3", "GND", "GPIO0", "GPIO1", "GPIO3", "GPIO4"],
      },
      {
        id: "soil-sensor",
        name: "Capacitive Soil Moisture Probe",
        role: "Soil Moisture Sensor",
        description:
          "Corrosion-resistant capacitive probe with an analog output; unlike a resistive fork it does not electroplate itself away over a season.",
        category: "sensor",
        domain: "electrical",
        qty: 1,
        unitCost: 3.5,
        pins: ["VCC", "GND", "AOUT"],
      },
      {
        id: "float",
        name: "Vertical Float Switch",
        role: "Water Level Sensor",
        description: "Reed float in the reservoir wall that opens as the level drops below the pump inlet.",
        category: "sensor",
        domain: "electrical",
        qty: 1,
        unitCost: 2.2,
        pins: ["SIG", "COM"],
      },
      {
        id: "button",
        name: "Momentary Push Button",
        role: "Manual Water Button",
        description: "Panel button on the enclosure lid that triggers one dose without waiting for the moisture threshold.",
        category: "sensor",
        domain: "electrical",
        qty: 1,
        unitCost: 0.6,
        pins: ["SIG", "GND"],
      },
      {
        id: "pump",
        name: "5V Submersible Micro Pump",
        role: "Irrigation Pump",
        description: "Brushed diaphragm pump sitting in the reservoir, roughly 100 L/h through 6mm tubing at this head height.",
        category: "actuator",
        domain: "electrical",
        qty: 1,
        unitCost: 4.8,
        pins: ["V+", "V-"],
      },
      {
        id: "mosfet",
        name: "IRL540N Low-Side Switch Board",
        role: "Pump Switch",
        description:
          "Logic-level MOSFET board switching the pump's ground return, with a flyback diode across the load terminals to absorb the motor's turn-off spike.",
        category: "module",
        domain: "electrical",
        qty: 1,
        unitCost: 2.4,
        pins: ["VIN", "GND", "SIG", "OUT+", "OUT-"],
      },
      {
        id: "psu",
        name: "5V 2A Wall Adapter",
        role: "Supply",
        description: "Sealed mains adapter feeding the whole system; only its 5V output ever goes near the reservoir.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 7.0,
        pins: ["+5V", "GND"],
      },
      {
        id: "enclosure",
        name: "IP54 Wall-Mount Enclosure",
        role: "Electronics Housing",
        description:
          "Hinged ABS box mounted above the waterline, holding the controller and switch board, with glands for the pump and probe leads.",
        category: "enclosure",
        domain: "mechanical",
        qty: 1,
        unitCost: 8.0,
      },
      {
        id: "reservoir-lid",
        name: "Reservoir Lid",
        role: "Reservoir Cover",
        description:
          "Snap-on lid with a tubing pass-through, a float switch boss, and a fill port; keeps dust and mosquitoes out of standing water.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 2.8,
        printSettings: "PETG · 30% infill, 0.2mm layer, 3 perimeters",
      },
      {
        id: "pump-mount",
        name: "Pump Mount Cradle",
        role: "Pump Cradle",
        description: "Cradle holding the pump 8mm off the reservoir floor so it draws water rather than settled sediment.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 1.4,
        printSettings: "PETG · 40% infill, 0.2mm layer",
      },
      {
        id: "probe-collar",
        name: "Probe Collar",
        role: "Probe Depth Guide",
        description: "Split collar that clamps the capacitive probe at a repeatable depth and keeps its electronics above the soil line.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 0.8,
        printSettings: "PETG · 40% infill, 0.2mm layer",
      },
      {
        id: "cable-clips",
        name: "Cable Clips",
        role: "Cable Management",
        description: "Adhesive-backed clips routing the pump and probe leads along the pot rim in a tidy drip loop.",
        category: "print3d",
        domain: "mechanical",
        qty: 6,
        unitCost: 0.2,
        printSettings: "PETG · 25% infill, 0.2mm layer",
      },
      {
        id: "reservoir",
        name: "3L Reservoir Tub",
        role: "Water Store",
        description: "Opaque food-safe tub sized for roughly two weeks of a medium pot's demand; opaque matters, or it grows algae.",
        category: "misc",
        domain: "mechanical",
        qty: 1,
        unitCost: 6.0,
      },
      {
        id: "tubing",
        name: "6mm Silicone Tubing",
        role: "Delivery Line",
        description: "One metre of soft silicone tubing from the pump outlet to a loop laid on the soil surface.",
        category: "misc",
        domain: "mechanical",
        qty: 1,
        unitCost: 3.0,
      },
      {
        id: "hardware",
        name: "M3 Screws + Heat-Set Inserts",
        role: "Fastener Set",
        description: "M3 screws, brass inserts, and nylon washers for the lid, cradle, and enclosure mounts.",
        category: "misc",
        domain: "mechanical",
        qty: 10,
        unitCost: 0.2,
      },
    ],
    connections: [
      { id: "c1", from: { part: "psu", pin: "+5V" }, to: { part: "esp32c3", pin: "5V" }, net: "power", label: "5V" },
      { id: "c2", from: { part: "psu", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
      { id: "c3", from: { part: "psu", pin: "+5V" }, to: { part: "mosfet", pin: "VIN" }, net: "power", label: "5V" },
      { id: "c4", from: { part: "psu", pin: "GND" }, to: { part: "mosfet", pin: "GND" }, net: "ground" },
      { id: "c5", from: { part: "mosfet", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground", label: "common ground" },
      { id: "c6", from: { part: "esp32c3", pin: "3V3" }, to: { part: "soil-sensor", pin: "VCC" }, net: "power", label: "3.3V" },
      { id: "c7", from: { part: "esp32c3", pin: "GND" }, to: { part: "soil-sensor", pin: "GND" }, net: "ground" },
      { id: "c8", from: { part: "soil-sensor", pin: "AOUT" }, to: { part: "esp32c3", pin: "GPIO0" }, net: "data", label: "analog" },
      { id: "c9", from: { part: "esp32c3", pin: "GPIO4" }, to: { part: "mosfet", pin: "SIG" }, net: "data", label: "gate" },
      { id: "c10", from: { part: "mosfet", pin: "OUT+" }, to: { part: "pump", pin: "V+" }, net: "power", label: "pump 5V" },
      { id: "c11", from: { part: "mosfet", pin: "OUT-" }, to: { part: "pump", pin: "V-" }, net: "power", label: "switched return" },
      { id: "c12", from: { part: "float", pin: "SIG" }, to: { part: "esp32c3", pin: "GPIO3" }, net: "data", label: "level" },
      { id: "c13", from: { part: "float", pin: "COM" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
      { id: "c14", from: { part: "button", pin: "SIG" }, to: { part: "esp32c3", pin: "GPIO1" }, net: "data", label: "manual run" },
      { id: "c15", from: { part: "button", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
    ],
    assembly: [
      {
        part: "enclosure",
        children: [
          { part: "esp32c3" },
          { part: "mosfet" },
          { part: "psu" },
          { part: "button" },
          { part: "cable-clips" },
          { part: "hardware" },
          { part: "probe-collar", children: [{ part: "soil-sensor" }] },
          {
            part: "reservoir",
            children: [
              {
                part: "reservoir-lid",
                children: [{ part: "float" }, { part: "pump-mount", children: [{ part: "pump" }] }],
              },
              { part: "tubing" },
            ],
          },
        ],
      },
    ],
    tools: [
      "3D printer (capable of PETG)",
      "Soldering station with fine tip",
      "Wire strippers",
      "Heat-set insert tool or fine soldering tip",
      "M3 hex driver",
      "Digital multimeter",
      "USB-C cable",
      "Hobby knife",
    ],
    assumptions: [
      "An indoor outlet within reach of the adapter cord; only its 5V side goes near water",
      "A 2.4GHz Wi-Fi network and an MQTT broker or webhook to receive alerts",
      "One medium pot with a drainage tray, watered from a reservoir standing beside it",
      "Basic familiarity with flashing ESP32 firmware (Arduino or PlatformIO)",
    ],
    instructions: [
      {
        id: "1",
        title: "Fabricate",
        steps: [
          {
            id: "1.1",
            title: "Print the lid, cradle, collar, and clips",
            detail:
              "Print all four parts in PETG — PLA creeps and eventually sags in a warm, permanently damp reservoir. Give the lid 3 perimeters so the tubing pass-through stays watertight against the grommet.",
            tools: ["3D printer (capable of PETG)"],
            parts: ["reservoir-lid", "pump-mount", "probe-collar", "cable-clips"],
          },
          {
            id: "1.2",
            title: "Open the lid and cut the delivery line",
            detail:
              "Trim the lid's fill port and tubing pass-through to a clean fit on the tub rim, then cut the silicone line long enough to reach the pot with a drip loop below the enclosure.",
            tools: ["Hobby knife"],
            parts: ["reservoir-lid", "reservoir", "tubing"],
          },
          {
            id: "1.3",
            title: "Install inserts and mount points",
            detail:
              "Sink brass inserts into the lid boss and the cradle, and fit the enclosure's cable glands. Keep every insert square as it melts in or the lid will not sit flat.",
            tools: ["Heat-set insert tool or fine soldering tip"],
            parts: ["reservoir-lid", "pump-mount", "enclosure", "hardware"],
          },
        ],
      },
      {
        id: "2",
        title: "Wire",
        steps: [
          {
            id: "2.1",
            title: "Bring in the 5V supply",
            detail:
              "Land the adapter's output on a terminal pair inside the enclosure, then feed both the controller's 5V pin and the switch board's VIN from it, with a shared ground back to the controller.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["psu", "esp32c3", "mosfet"],
          },
          {
            id: "2.2",
            title: "Wire the pump through the switch board",
            detail:
              "Pump leads to the board's load terminals and GPIO4 to the gate input. Never drive the pump straight from a GPIO — its stall current is many times what the pin can source.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["mosfet", "pump", "esp32c3"],
          },
          {
            id: "2.3",
            title: "Wire the probe and float switch",
            detail:
              "3.3V and ground to the probe with its analog output on GPIO0, and the float switch between GPIO3 and ground using the internal pull-up. Use silicone-jacketed wire for anything entering the reservoir.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["soil-sensor", "float", "esp32c3"],
          },
          {
            id: "2.4",
            title: "Fit the button and check the rails",
            detail:
              "Solder the panel button between GPIO1 and ground, then confirm 5.0V at the switch board, 3.3V at the probe connector, and no short between rails before the adapter stays plugged in.",
            tools: ["Soldering station with fine tip", "Digital multimeter"],
            parts: ["button", "esp32c3", "mosfet"],
          },
        ],
      },
      {
        id: "3",
        title: "Bring-up",
        steps: [
          {
            id: "3.1",
            title: "Flash firmware and join Wi-Fi",
            detail:
              "Flash the irrigation firmware over USB, set the network credentials and broker address, and confirm the first status message lands with the pump still disabled.",
            tools: ["USB-C cable"],
            parts: ["esp32c3"],
          },
          {
            id: "3.2",
            title: "Calibrate dry and wet readings",
            detail:
              "Record the probe reading in open air and again in a glass of water, then set the dry threshold roughly a third of the way up that span for a typical potting mix.",
            tools: ["USB-C cable"],
            parts: ["soil-sensor", "esp32c3"],
          },
          {
            id: "3.3",
            title: "Prime the pump and time one dose",
            detail:
              "With the tubing pointed into a measuring jug, run the pump for ten seconds and measure the volume; set the dose duration from that rate rather than guessing millilitres.",
            tools: ["USB-C cable"],
            parts: ["pump", "tubing", "reservoir"],
          },
          {
            id: "3.4",
            title: "Prove the dry-run cutoff",
            detail:
              "Hold the float in its low position and confirm the controller refuses a manual dose and raises the low-water alert. This interlock is the one behaviour worth testing twice.",
            tools: ["USB-C cable"],
            parts: ["float", "pump", "esp32c3", "button"],
          },
        ],
      },
      {
        id: "4",
        title: "Assemble",
        steps: [
          {
            id: "4.1",
            title: "Fit the pump and lid to the reservoir",
            detail:
              "Screw the cradle to the lid underside, seat the pump in it, fit the float in its boss, and snap the lid onto the filled tub with the tubing through its pass-through.",
            tools: ["M3 hex driver"],
            parts: ["reservoir", "reservoir-lid", "pump-mount", "pump", "float", "hardware"],
          },
          {
            id: "4.2",
            title: "Set the probe depth",
            detail:
              "Clamp the collar so the probe sits mid root-ball with its electronics well clear of the soil, then press it in beside the plant rather than through the root mass.",
            tools: ["M3 hex driver"],
            parts: ["probe-collar", "soil-sensor"],
          },
          {
            id: "4.3",
            title: "Mount the enclosure and dress the cabling",
            detail:
              "Hang the enclosure above the waterline, clip the pump and probe leads along the pot rim with a drip loop below each gland, and lay the tubing loop on the soil surface.",
            tools: ["M3 hex driver"],
            parts: ["enclosure", "esp32c3", "psu", "mosfet", "button", "cable-clips", "tubing"],
          },
        ],
      },
    ],
  },
};
