import type { ProjectRecord } from "../schema";

export const weatherStation: ProjectRecord = {
  slug: "balcony-weather-station",
  author: "openblueprint",
  source: "seed",
  stars: 7,
  createdAt: "2026-08-20T09:00:00Z",
  cover: { glyph: "☀", hueA: "#38d1b4", hueB: "#fbbf24" },
  pkg: {
    name: "Balcony Weather Station",
    summary:
      "This solar-powered weather station samples temperature, humidity, barometric pressure, UV index, and wind speed from a balcony rail mount. An ESP32-C3 wakes on a timer, reads the I2C sensor bus and pulse anemometer, pushes telemetry over Wi-Fi to any MQTT broker, and shows current conditions on a small OLED. A 1W solar panel and 18650 cell keep it running indefinitely off-grid.",
    tags: ["SOLAR POWERED", "WI-FI TELEMETRY", "WEATHERPROOF", "LOW POWER"],
    parts: [
      {
        id: "esp32c3",
        name: "ESP32-C3 DevKit",
        role: "Main Logic Controller",
        description:
          "RISC-V microcontroller with Wi-Fi. Handles sensor sampling, deep sleep scheduling, and MQTT telemetry.",
        category: "mcu",
        domain: "electrical",
        qty: 1,
        unitCost: 4.5,
        pins: ["3V3", "GND", "SDA", "SCL", "GPIO4", "ADC0"],
      },
      {
        id: "bme280",
        name: "Bosch BME280",
        role: "Climate Sensor",
        description:
          "Combined temperature, humidity, and barometric pressure sensor on the I2C bus.",
        category: "sensor",
        domain: "electrical",
        qty: 1,
        unitCost: 6.0,
        pins: ["VCC", "GND", "SDA", "SCL"],
      },
      {
        id: "anemometer",
        name: "3-Cup Reed Anemometer",
        role: "Wind Speed Sensor",
        description:
          "Rotating cup assembly closing a reed switch once per revolution; wind speed derived from pulse rate.",
        category: "sensor",
        domain: "electrical",
        qty: 1,
        unitCost: 12.0,
        pins: ["SIG", "GND"],
      },
      {
        id: "uv-sensor",
        name: "GUVA-S12SD",
        role: "UV Index Sensor",
        description: "Analog UV photodiode module; output voltage maps to UV index.",
        category: "sensor",
        domain: "electrical",
        qty: 1,
        unitCost: 3.0,
        pins: ["VCC", "GND", "OUT"],
      },
      {
        id: "oled",
        name: "SSD1306 0.96\" OLED",
        role: "Conditions Display",
        description: "128×64 monochrome OLED showing live readings, shares the I2C bus.",
        category: "display",
        domain: "electrical",
        qty: 1,
        unitCost: 5.0,
        pins: ["VCC", "GND", "SDA", "SCL"],
      },
      {
        id: "solar-panel",
        name: "6V 1W Solar Panel",
        role: "Energy Harvester",
        description: "Compact epoxy panel angled toward the sun to recharge the cell.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 8.0,
        pins: ["V+", "V-"],
      },
      {
        id: "tp4056",
        name: "TP4056 Charge Module",
        role: "Charge Controller",
        description:
          "Li-ion charge and protection board between the panel and the cell, with load sharing output.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 2.0,
        pins: ["IN+", "IN-", "BAT+", "BAT-", "OUT+", "OUT-"],
      },
      {
        id: "cell18650",
        name: "18650 Li-ion Cell + Holder",
        role: "Energy Storage",
        description: "3.7V 2600mAh cell buffering solar input across nights and overcast days.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 6.5,
        pins: ["B+", "B-"],
      },
      {
        id: "ldo",
        name: "MCP1700-3302E LDO",
        role: "3.3V Regulator",
        description: "Ultra-low quiescent current regulator feeding the logic rail during deep sleep.",
        category: "power",
        domain: "electrical",
        qty: 1,
        unitCost: 0.6,
        pins: ["VIN", "GND", "VOUT"],
      },
      {
        id: "enclosure",
        name: "IP65 Vented Enclosure",
        role: "Weatherproof Housing",
        description: "Sealed ABS enclosure with membrane vent housing logic and power electronics.",
        category: "enclosure",
        domain: "mechanical",
        qty: 1,
        unitCost: 9.0,
      },
      {
        id: "rad-shield",
        name: "Radiation Shield Stack",
        role: "Sensor Screen",
        description:
          "Stacked-plate Stevenson screen keeping direct sun off the BME280 while letting air flow.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 2.5,
        printSettings: "PETG · 30% infill, 0.2mm layer",
      },
      {
        id: "mast-arm",
        name: "Anemometer Mast Arm",
        role: "Wind Sensor Boom",
        description: "Rail-clamp boom lifting the anemometer into clean airflow above the balcony rail.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 3.0,
        printSettings: "PETG · 50% infill, 0.2mm layer, 4 perimeters",
      },
      {
        id: "panel-bracket",
        name: "Panel Tilt Bracket",
        role: "Solar Mount",
        description: "Adjustable-angle bracket aiming the panel at seasonal sun elevation.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 2.0,
        printSettings: "PETG · 40% infill, 0.2mm layer",
      },
      {
        id: "wall-plate",
        name: "Rail Mount Plate",
        role: "Main Mount",
        description: "Backing plate joining the enclosure to the balcony rail with zip-tie channels.",
        category: "print3d",
        domain: "mechanical",
        qty: 1,
        unitCost: 2.0,
        printSettings: "PETG · 50% infill, 0.2mm layer",
      },
      {
        id: "m3-hardware",
        name: "M3 Screws + Heat-Set Inserts",
        role: "Fastener Set",
        description: "Socket-head M3 screws and brass inserts for all printed joints.",
        category: "misc",
        domain: "mechanical",
        qty: 16,
        unitCost: 0.2,
      },
    ],
    connections: [
      { id: "c1", from: { part: "solar-panel", pin: "V+" }, to: { part: "tp4056", pin: "IN+" }, net: "power", label: "6V" },
      { id: "c2", from: { part: "solar-panel", pin: "V-" }, to: { part: "tp4056", pin: "IN-" }, net: "ground" },
      { id: "c3", from: { part: "tp4056", pin: "BAT+" }, to: { part: "cell18650", pin: "B+" }, net: "power", label: "3.7V" },
      { id: "c4", from: { part: "tp4056", pin: "BAT-" }, to: { part: "cell18650", pin: "B-" }, net: "ground" },
      { id: "c5", from: { part: "tp4056", pin: "OUT+" }, to: { part: "ldo", pin: "VIN" }, net: "power", label: "VBAT" },
      { id: "c6", from: { part: "tp4056", pin: "OUT-" }, to: { part: "ldo", pin: "GND" }, net: "ground" },
      { id: "c7", from: { part: "ldo", pin: "VOUT" }, to: { part: "esp32c3", pin: "3V3" }, net: "power", label: "3.3V" },
      { id: "c8", from: { part: "ldo", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
      { id: "c9", from: { part: "bme280", pin: "SDA" }, to: { part: "esp32c3", pin: "SDA" }, net: "data", label: "I2C" },
      { id: "c10", from: { part: "bme280", pin: "SCL" }, to: { part: "esp32c3", pin: "SCL" }, net: "data", label: "I2C" },
      { id: "c11", from: { part: "bme280", pin: "VCC" }, to: { part: "esp32c3", pin: "3V3" }, net: "power", label: "3.3V" },
      { id: "c12", from: { part: "bme280", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
      { id: "c13", from: { part: "oled", pin: "SDA" }, to: { part: "esp32c3", pin: "SDA" }, net: "data", label: "I2C" },
      { id: "c14", from: { part: "oled", pin: "SCL" }, to: { part: "esp32c3", pin: "SCL" }, net: "data", label: "I2C" },
      { id: "c15", from: { part: "oled", pin: "VCC" }, to: { part: "esp32c3", pin: "3V3" }, net: "power", label: "3.3V" },
      { id: "c16", from: { part: "oled", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
      { id: "c17", from: { part: "anemometer", pin: "SIG" }, to: { part: "esp32c3", pin: "GPIO4" }, net: "data", label: "pulse" },
      { id: "c18", from: { part: "anemometer", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
      { id: "c19", from: { part: "uv-sensor", pin: "OUT" }, to: { part: "esp32c3", pin: "ADC0" }, net: "data", label: "analog" },
      { id: "c20", from: { part: "uv-sensor", pin: "VCC" }, to: { part: "esp32c3", pin: "3V3" }, net: "power", label: "3.3V" },
      { id: "c21", from: { part: "uv-sensor", pin: "GND" }, to: { part: "esp32c3", pin: "GND" }, net: "ground" },
    ],
    assembly: [
      {
        part: "enclosure",
        children: [
          { part: "wall-plate" },
          { part: "esp32c3" },
          { part: "tp4056" },
          { part: "ldo" },
          { part: "cell18650" },
          { part: "oled" },
          { part: "panel-bracket", children: [{ part: "solar-panel" }] },
          { part: "rad-shield", children: [{ part: "bme280" }, { part: "uv-sensor" }] },
          { part: "mast-arm", children: [{ part: "anemometer" }] },
          { part: "m3-hardware" },
        ],
      },
    ],
    tools: [
      "3D printer (capable of PETG)",
      "Soldering station with fine tip",
      "Heat-set insert tool or fine soldering tip",
      "M3 hex driver",
      "Digital multimeter",
      "Wire strippers",
      "USB-C cable",
    ],
    assumptions: [
      "2.4GHz Wi-Fi network reachable from the balcony",
      "An MQTT broker or dashboard endpoint to receive telemetry",
      "Balcony rail with partial direct sun for the panel",
      "Basic familiarity with flashing ESP32 firmware (Arduino or PlatformIO)",
    ],
    instructions: [
      {
        id: "1",
        title: "Fabricate",
        steps: [
          {
            id: "1.1",
            title: "3D print shield, brackets, and mount plate",
            detail:
              "Print the radiation shield stack, anemometer mast arm, panel tilt bracket, and rail mount plate in PETG for UV resistance. Use the listed infill per part; the mast arm needs 4 perimeters for stiffness.",
            tools: ["3D printer (capable of PETG)"],
            parts: ["rad-shield", "mast-arm", "panel-bracket", "wall-plate"],
          },
          {
            id: "1.2",
            title: "Install heat-set inserts",
            detail:
              "Press M3 brass inserts into the mount plate, shield cap, and bracket bosses with a heated insert tool. Keep the insert square as it melts in.",
            tools: ["Heat-set insert tool or fine soldering tip"],
            parts: ["m3-hardware", "wall-plate", "rad-shield", "panel-bracket"],
          },
          {
            id: "1.3",
            title: "Dry-fit the enclosure stack",
            detail:
              "Clamp the mount plate to the enclosure, hang the mast arm and shield, and confirm nothing fouls the panel's tilt sweep before any wiring.",
            tools: ["M3 hex driver"],
            parts: ["enclosure", "wall-plate", "mast-arm", "rad-shield", "panel-bracket"],
          },
        ],
      },
      {
        id: "2",
        title: "Wire",
        steps: [
          {
            id: "2.1",
            title: "Solder the solar charge chain",
            detail:
              "Panel to TP4056 IN, cell holder to BAT, and OUT to the MCP1700 input. Mind polarity twice — the TP4056 does not forgive a reversed cell.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["solar-panel", "tp4056", "cell18650", "ldo"],
          },
          {
            id: "2.2",
            title: "Wire the I2C bus",
            detail:
              "Daisy-chain SDA and SCL from the ESP32 to the BME280 and OLED with 3.3V and ground. Keep the run to the shield under 30cm.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["esp32c3", "bme280", "oled"],
          },
          {
            id: "2.3",
            title: "Wire anemometer and UV sensor",
            detail:
              "Reed switch signal to GPIO4 with the internal pull-up, UV output to ADC0. Use silicone-jacketed wire for the outdoor runs.",
            tools: ["Soldering station with fine tip", "Wire strippers"],
            parts: ["anemometer", "uv-sensor", "esp32c3"],
          },
          {
            id: "2.4",
            title: "Verify rails before first power-up",
            detail:
              "With the cell installed and panel covered, confirm 3.3V at the ESP32 and no shorts between rails.",
            tools: ["Digital multimeter"],
            parts: ["ldo", "esp32c3"],
          },
        ],
      },
      {
        id: "3",
        title: "Bring-up",
        steps: [
          {
            id: "3.1",
            title: "Flash firmware over USB",
            detail:
              "Flash the station firmware, set Wi-Fi credentials and broker address, and confirm serial output shows a clean boot.",
            tools: ["USB-C cable"],
            parts: ["esp32c3"],
          },
          {
            id: "3.2",
            title: "Confirm both I2C devices enumerate",
            detail:
              "Run an I2C scan; the BME280 (0x76) and OLED (0x3C) must both appear before closing the enclosure.",
            tools: ["USB-C cable"],
            parts: ["esp32c3", "bme280", "oled"],
          },
          {
            id: "3.3",
            title: "Calibrate wind pulses",
            detail:
              "Spin the cups a known number of turns and check the pulse count; set the pulses-per-revolution constant in firmware.",
            tools: ["USB-C cable"],
            parts: ["anemometer", "esp32c3"],
          },
          {
            id: "3.4",
            title: "Verify telemetry end-to-end",
            detail:
              "Watch one full sleep/wake/publish cycle land on the broker and render on the OLED before deployment.",
            tools: ["USB-C cable"],
            parts: ["esp32c3", "oled"],
          },
        ],
      },
      {
        id: "4",
        title: "Assemble",
        steps: [
          {
            id: "4.1",
            title: "Mount electronics in the enclosure",
            detail:
              "Fasten the ESP32, TP4056, LDO, and cell holder to the enclosure standoffs; route sensor leads through the gland.",
            tools: ["M3 hex driver"],
            parts: ["enclosure", "esp32c3", "tp4056", "ldo", "cell18650"],
          },
          {
            id: "4.2",
            title: "Hang shield, mast, and panel",
            detail:
              "Bolt the radiation shield below the enclosure, the mast arm above rail height, and the panel bracket facing the sun path.",
            tools: ["M3 hex driver"],
            parts: ["rad-shield", "mast-arm", "panel-bracket", "solar-panel", "m3-hardware"],
          },
          {
            id: "4.3",
            title: "Seal and install on the rail",
            detail:
              "Close the lid on the gasket, zip-tie the mount plate to the rail, and confirm the OLED is readable from the balcony.",
            tools: ["M3 hex driver"],
            parts: ["enclosure", "wall-plate", "oled"],
          },
        ],
      },
    ],
  },
};
